### ISSUE TITLE
not working + sh1tty virus

### ISSUE THREAD

**Issue by xrmna** [Bleu-No/Fuck-Ares#1]
not working, code is definitely bad, nothing to see with ares, i know what i'm sayin i bought it kiddo
go buy you a life nga

**Comment by billythegoat356** [comment]
you bought a tool that was using nuitka and pyarmor (which are FREE) for 30 dollars LMAO
imagine paying 30 dollars for something free loll

**Comment by Bleu-No** [comment]
So hello, you're either a Venax dog or you're Venax. So look, the code works just fine, you're just too stupid to make it work. Then the code is not the same, because I'm not Venax and I don't know if you can read, but this is not over.

**Comment by PndaBoi** [comment]
Send me proof that's it's a shit virus @xrmna
