### ISSUE TITLE
Problème avec fichier email.txt

### ISSUE THREAD

**Issue by Samus0754** [Bleu-No/Fuck-Ares#10]
Salut, j'ai installé tous les trucs que tu dis de faire dans le readme, je mets le chemin d'accès du fichier pour le email.txt, et ça me dit qu'il trouve pas le fichier.

voici l'erreur : 

C:\Users\admin\Desktop\XCreator-Discord-main\src\navigator.ts:521
            this.browser.close();
                         ^
TypeError: Cannot read properties of undefined (reading 'close')
    at Navigator.loadEmailsFile (C:\Users\admin\Desktop\XCreator-Discord-main\src\navigator.ts:521:26)
    at Navigator.init (C:\Users\admin\Desktop\XCreator-Discord-main\src\navigator.ts:82:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

en espérant que ça t'aide pour m'aider a fix le problème.

bonne soirée :)

**Comment by Bleu-No** [comment]
Salut ! Alors ,déjà tu n'es pas sur le bon repos et puis j'ai abandonnée ce projet depuis bien longtemps et qui dit abandonnée dit que je n'aide personne. Mais bon vu que je suis de bonne humeur passe en MP Discord pour que je t'aide, mais juste cette fois 👍🏻
