### ISSUE TITLE
you're a shame lol it's not ares at all 🤣

### ISSUE THREAD

**Issue by nostrals** [Bleu-No/Fuck-Ares#2]
i already have ares actually and ur garbage code has nothing to see with it actually
i joined github just to say it because it's a real shame you're not even able to skid people correctly.
never seen a fool like u before lmao, waste of time for crap code at the end, that's what u did fool 😂

**Comment by billythegoat356** [comment]
youre the shame here. you bought a tool that was using nuitka and pyarmor (which are FREE) for 30 dollars LMAO
imagine paying 30 dollars for something free loll

**Comment by Bleu-No** [comment]
You are really very stupid. You can't even read, because I still haven't finished and it then I'm not going to spend time on this crap. Then it's your problem if you want to buy this crap that only uses Nuitka and other obfuscators. Know that without Nuitka it's nothing.

**Comment by PndaBoi** [comment]
Sounds like someone needs to go get a refund
